services:
  - type: web
    name: leo-digital-twin-backend
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    pythonVersion: 3.12.16  # <--- add this line
    envVars:
      # Secrets from Render Dashboard
      - key: FIRMS_KEY
        fromSecret: FIRMS_KEY
      - key: CDSE_CLIENT_ID
        fromSecret: CDSE_CLIENT_ID
      - key: CDSE_CLIENT_SECRET
        fromSecret: CDSE_CLIENT_SECRET

      # Non-secret defaults
      - key: FIRMS_SOURCE
        value: VIIRS_NOAA20_NRT
      - key: NWS_USER_AGENT
        value: "LEO-DigitalTwin/1.0 (jajdarin@gmail.com)"
